name: example-servant-minimal

ghc-options: -Wall

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec
      - example-servant-minimal
      - servant-client
      - http-client
      - http-types

library:
  source-dirs:
    - src

executables:
  example-servant-minimal:
    main: exe/Main.hs
    dependencies:
      - example-servant-minimal

dependencies:
  - base
  - servant
  - servant-server
  - transformers
  - aeson
  - wai
  - warp
  - servant-client
  - servant-js
  - servant-foreign
  - either
  - http-client
  - js-jquery
  - text
